DROP TABLE IF EXISTS vacations;
DROP TABLE IF EXISTS employees;
DROP TABLE IF EXISTS departments;

-- Створюємо таблицю відділів
CREATE TABLE IF NOT EXISTS departments (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

-- Створюємо таблицю працівників
CREATE TABLE IF NOT EXISTS employees (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    position VARCHAR(255) NOT NULL,
    hire_date DATE NOT NULL,
    annual_days INT NOT NULL,
    department_id INT NOT NULL,
    carryover_days INT NOT NULL,
    FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE CASCADE
);

-- Створюємо таблицю відпусток
CREATE TABLE IF NOT EXISTS vacations (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id INT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    vacation_type VARCHAR(255) NOT NULL,
    FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE
);