package db;

import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.Properties;

public class DatabaseManager {
    private static String url;
    private static String user;
    private static String password;

    static {
        try (InputStream input = DatabaseManager.class.getClassLoader().getResourceAsStream("db.properties")) {
            Properties prop = new Properties();
            if (input == null) {
                throw new RuntimeException("Sorry, unable to find db.properties");
            }
            prop.load(input);

            Class.forName(prop.getProperty("db.driver", "org.h2.Driver"));
            url = prop.getProperty("db.url");
            user = prop.getProperty("db.user", "sa");
            password = prop.getProperty("db.password", "");

        } catch (Exception e) {
            e.printStackTrace();
            throw new RuntimeException("Failed to initialize database configuration", e);
        }
    }

    public static Connection getConnection() throws java.sql.SQLException {
        Connection conn = DriverManager.getConnection(url, user, password);
        createTablesIfNotExist(conn);
        return conn;
    }

    private static void createTablesIfNotExist(Connection conn) {
        try (Statement stmt = conn.createStatement()) {
            // Створюємо таблицю відділів
            stmt.execute("CREATE TABLE IF NOT EXISTS departments (" +
                    "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "name VARCHAR(255) NOT NULL, " +
                    "department_name VARCHAR(255) DEFAULT ''" +
                    ");");

            // Створюємо таблицю співробітників з точними назвами полів із твого сервісу
            stmt.execute("CREATE TABLE IF NOT EXISTS employees (" +
                    "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "full_name VARCHAR(255) NOT NULL, " +
                    "position VARCHAR(255) NOT NULL, " +
                    "hire_date DATE NOT NULL, " +
                    "annual_paid_leave_days INT NOT NULL, " +
                    "carryover_paid_leave_days INT NOT NULL, " +
                    "department_id INT NOT NULL, " +
                    "FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE CASCADE" +
                    ");");

            // Створюємо таблицю відпусток, оскільки твій сервіс має метод addVacation
            stmt.execute("CREATE TABLE IF NOT EXISTS vacations (" +
                    "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "employee_id INT NOT NULL, " +
                    "start_date DATE NOT NULL, " +
                    "end_date DATE NOT NULL, " +
                    "vacation_type VARCHAR(255) NOT NULL, " +
                    "FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE" +
                    ");");

            System.out.println(" Локальні таблиці H2 успішно синхронізовано з кодом сервісів!");
        } catch (Exception e) {
            System.err.println("Помилка створення таблиць: " + e.getMessage());
            e.printStackTrace();
        }
    }
}